// questions.js
// ---------------------------------------------
window.QUESTION_POOL = [
  // ===== Hauptstädte ===== //
  { q: "Die Hauptstadt von Frankreich ist …", a: "Paris" },
  { q: "Die Hauptstadt von Italien ist …", a: "Rom" },
  { q: "Die Hauptstadt von Schweiz ist …", a: "Bern" },
  { q: "Die Hauptstadt von Spanien ist …", a: "Madrid" },
  { q: "Die Hauptstadt von Portugal ist …", a: "Lissabon" },
  { q: "Die Hauptstadt von Norwegen ist …", a: "Oslo" },
  { q: "Die Hauptstadt von Schweden ist …", a: "Stockholm" },
  { q: "Die Hauptstadt von Finnland ist …", a: "Helsinki" },
  { q: "Die Hauptstadt von Polen ist …", a: "Warschau" },
  { q: "Die Hauptstadt von Tschechien ist …", a: "Prag" },
  { q: "Die Hauptstadt von Malta ist …", a: "Valletta" },
  { q: "Die Hauptstadt von Türkei ist …", a: "Ankara" },
  { q: "Die Hauptstadt von Zypern ist …", a: "Nikosia" },
  { q: "Die Hauptstadt von Griechenland ist …", a: "Athen" },
  { q: "Die Hauptstadt von Bulgarien ist …", a: "Sofia" },
  { q: "Die Hauptstadt von Ukraine ist …", a: "Kiew" },
  { q: "Die Hauptstadt von Rumänien ist …", a: "Bukarest" },
  { q: "Die Hauptstadt von China ist …", a: "Peking (Beijing)" },
  { q: "Die Hauptstadt von Indien ist …", a: "Neu-Delhi" },
  { q: "Die Hauptstadt von Pakistan ist …", a: "Islamabad" },
  { q: "Die Hauptstadt von Philippinen ist …", a: "Manila" },
  { q: "Die Hauptstadt von Australien ist …", a: "Canberra" },
  { q: "Die Hauptstadt von Neuseeland ist …", a: "Wellington" },
  { q: "Die Hauptstadt von Brasilien ist …", a: "Brasília" },
  { q: "Die Hauptstadt von Argentinien ist …", a: "Buenos Aires" },
  { q: "Die Hauptstadt von Kolumbien ist …", a: "Bogotá" },
  { q: "Die Hauptstadt von Kanada ist …", a: "Ottawa" },
  { q: "Die Hauptstadt von Mexiko ist …", a: "Mexiko-Stadt" },
  { q: "Die Hauptstadt von Vereinigte Staaten ist …", a: "Washington, D.C." },
  { q: "Die Hauptstadt von Tunesien ist …", a: "Tunis" },
  { q: "Die Hauptstadt von Südafrika ist …", a: "Pretoria" },
  { q: "Die Hauptstadt von Ägypten ist …", a: "Kairo" },
  { q: "Die Hauptstadt von Algerien ist …", a: "Algier" },
  { q: "Die Hauptstadt von Marokko ist …", a: "Rabat" },
  { q: "Die Hauptstadt von Japan ist …", a: "Tokio" },
  { q: "Die Hauptstadt von Südkorea ist …", a: "Seoul" },
  { q: "Die Hauptstadt von Nordkorea ist …", a: "Pjöngjang" },
  { q: "Die Hauptstadt von Vietnam ist …", a: "Hanoi" },
  // ===== US-Politik ===== //
  { q: "Der wievielte US-Präsident war George Washington?", a: "1" },
  { q: "Der wievielte US-Präsident war Joe Biden?", a: "46" },
  { q: "Joe Biden schlug im US-Präsidentschaftswahlkampf seinen republikanischen Gegenkandidaten Donald ...", a: "Trump" },
  { q: "Wie viele Sterne sind auf der US-Flagge?", a: "50" },
  { q: "Welches Tier ist das Symbol der Demokratischen Partei?", a: "Esel" },
  { q: "Welches Tier ist das Symbol der Republikanischen Partei?", a: "Elefant" },
  { q: "Wie viele Senatoren gibt es im US-Senat?", a: "100" },
  { q: "Wie oft können US-Präsidenten gewählt werden?", a: "Zweimal" },
  { q: "Wie heißt der Skandal, der 1974 zum Rücktritt von Präsident Richard Nixon führte?", a: "Watergate-Skandal" },
  { q: "Wie nennt man US-Bundesstaaten, in denen keine der beiden großen Parteien eine verlässliche Mehrheit hat und in dem die Mehrheit hin- und herwechseln kann?", a: "Swing States" },
  { q: "Wie nennt man das Gremium, das in den USA den Präsidenten offiziell wählt?", a: "Electoral College" },
  { q: "Was ist ein gängiger Begriff für einen Präsidenten, der zwar noch im Amt ist, aber bereits abgewählt oder amtszeitbeschränkt ist?", a: "Lame Duck" },
  { q: "Wie heißt das Büro des US-Präsidenten im Weißen Haus?", a: "Oval Office" },
  { q: "Die ehemalige Praktikantin, die bekannt dafür wurde eine Affäre mit US-Präsident Bill Clinton zu haben, hieß Monica ...", a: "Lewinsky" },
  // ===== Reime ===== //
  { q: "Welches optische Hilfsmittel reimt sich auf Stille?", a: "Brille" },
  { q: "Welches Alltagswerkzeug reimt sich auf Klammer?", a: "Hammer" },
  // ===== KFZ-Kennzeichen ===== //
  { q: "Das KFZ-Kennzeichen HB steht für welche deutsche Stadt?", a: "Bremen" },
  { q: "Das KFZ-Kennzeichen HH steht für welche deutsche Stadt?", a: "Hamburg" },
  { q: "Das KFZ-Kennzeichen B steht für welche deutsche Stadt?", a: "Berlin" },
  { q: "Das KFZ-Kennzeichen M steht für welche deutsche Stadt?", a: "München" },
  { q: "Das KFZ-Kennzeichen K steht für welche deutsche Stadt?", a: "Köln" },
  { q: "Das KFZ-Kennzeichen DD steht für welche deutsche Stadt?", a: "Dresden" },
  { q: "Das KFZ-Kennzeichen DO steht für welche deutsche Stadt?", a: "Dortmund" },
  { q: "Das KFZ-Kennzeichen DU steht für welche deutsche Stadt?", a: "Duisburg" },
  { q: "Das KFZ-Kennzeichen E steht für welche deutsche Stadt?", a: "Essen" },
  { q: "Das KFZ-Kennzeichen F steht für welche deutsche Stadt?", a: "Frankfurt am Main" },
  { q: "Das KFZ-Kennzeichen S steht für welche deutsche Stadt?", a: "Stuttgart" },
  { q: "Das KFZ-Kennzeichen H steht für welche deutsche Stadt?", a: "Hannover" },
  { q: "Das KFZ-Kennzeichen N steht für welche deutsche Stadt?", a: "Nürnberg" },
  { q: "Das KFZ-Kennzeichen MA steht für welche deutsche Stadt?", a: "Mannheim" },
  { q: "Das KFZ-Kennzeichen WOB steht für welche deutsche Stadt?", a: "Wolfsburg" },
  // ===== vor oder nach Chr. ===== //
  { q: "Der griechische Philosoph Sokrates starb 399 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Platon wurde 427 v. Chr. oder n. Chr. geboren?", a: "v. Chr." },
  { q: "Der Feldherr Alexander der Große starb 323 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der römische Diktator Julius Cäsar starb 44 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der römische Kaiser Augustus starb 14 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Jesus von Nazareth wurde um das Jahr 4 v. Chr. oder n. Chr. geboren?", a: "v. Chr." },
  { q: "Der römische Kaiser Nero starb 68 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der griechische Mathematiker Archimedes starb 212 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Aristoteles starb 322 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Feldherr Hannibal lebte 2. Jahrhundert v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Apostel Paulus starb um 64 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der ägyptische Pharao Tutanchamun starb um 1323 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Die Königin Kleopatra starb 30 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Konfuzius starb 479 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der römische Kaiser Konstantin der Große starb 337 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der jüdische König Herodes der Große starb 4 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Feldherr Spartakus starb 71 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Seneca starb 65 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der Dichter Homer lebte im 8. Jahrhundert v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Apostel Paulus starb um 64 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Nero starb 68 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Augustus starb 14 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Tiberius starb 37 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der Apostel Petrus starb um 64 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Caligula starb 41 v. Chr. oder n. Chr.?", a: "n. Chr." },
  // ===== Primzahl ===== //
  { q: "Welche Primzahl folgt auf 23?", a: "29" },
  { q: "Welche Primzahl folgt auf 29?", a: "31" },
  { q: "Welche Primzahl folgt auf 31?", a: "37" },
  { q: "Welche Primzahl folgt auf 37?", a: "41" },
  { q: "Welche Primzahl folgt auf 41?", a: "43" },
  { q: "Welche Primzahl folgt auf 43?", a: "47" },
  { q: "Welche Primzahl folgt auf 47?", a: "53" },
  { q: "Welche Primzahl folgt auf 53?", a: "59" },
  { q: "Welche Primzahl folgt auf 59?", a: "61" },
  { q: "Welche Primzahl folgt auf 61?", a: "67" },
  // ===== Sprichwörter ===== //
  { q: "Vervollständige folgendes Sprichwort: „Wer anderen eine Grube gräbt, …“", a: "fällt selbst hinein." },
  { q: "Vervollständige folgendes Sprichwort: „Morgenstund hat …“", a: "Gold im Mund." },
  { q: "Vervollständige folgendes Sprichwort: „Alle Wege führen …“", a: "nach Rom." },
  { q: "Vervollständige folgendes Sprichwort: „Ende gut, …“", a: "alles gut." },
  { q: "Vervollständige folgendes Sprichwort: „Stille Wasser sind …“", a: "tief." },
  { q: "Vervollständige folgendes Sprichwort: „Übung macht …“", a: "den Meister." },
  { q: "Vervollständige folgendes Sprichwort: „Eile mit …“", a: "Weile." },
  { q: "Vervollständige folgendes Sprichwort: „Kleider machen …“", a: "Leute." },
  { q: "Vervollständige folgendes Sprichwort: „Wie man in den Wald hineinruft, …“", a: "so schallt es heraus." },
  { q: "Vervollständige folgendes Sprichwort: „Der Apfel fällt nicht …“", a: "weit vom Stamm." },
  { q: "Vervollständige folgendes Sprichwort: „Viele Köche …“", a: "verderben den Brei." },
  { q: "Vervollständige folgendes Sprichwort: „Man soll den Tag nicht …“", a: "vor dem Abend loben." },
  { q: "Vervollständige folgendes Sprichwort: „Eine Hand wäscht …“", a: "die andere." },
  { q: "Vervollständige folgendes Sprichwort: „Der frühe Vogel …“", a: "fängt den Wurm." },
  { q: "Vervollständige folgendes Sprichwort: „In der Not frisst …“", a: "der Teufel Fliegen." },
  { q: "Vervollständige folgendes Sprichwort: „Was du nicht willst, das man dir tu, …“", a: "das füg auch keinem andern zu." },
  { q: "Vervollständige folgendes Sprichwort: „Wer rastet, …“", a: "der rostet." },
  { q: "Vervollständige folgendes Sprichwort: „Ein Unglück kommt …“", a: "selten allein." },
  { q: "Vervollständige folgendes Sprichwort: „Aus den Augen, …“", a: "aus dem Sinn." },
  { q: "Vervollständige folgendes Sprichwort: „Lügen haben …“", a: "kurze Beine." },
  { q: "Vervollständige folgendes Sprichwort: „Was lange währt, …“", a: "wird endlich gut." },
  { q: "Vervollständige folgendes Sprichwort: „Geteiltes Leid ist …“", a: "halbes Leid." },
  { q: "Vervollständige folgendes Sprichwort: „Reden ist Silber, …“", a: "Schweigen ist Gold." },
  { q: "Vervollständige folgendes Sprichwort: „Wer zuletzt lacht, …“", a: "lacht am besten." },
  { q: "Vervollständige folgendes Sprichwort: „Der Fisch stinkt vom …“", a: "Kopf her." },
  { q: "Vervollständige folgendes Sprichwort: „Not macht …“", a: "erfinderisch." },
  { q: "Vervollständige folgendes Sprichwort: „Liebe geht durch …“", a: "den Magen." },
  { q: "Vervollständige folgendes Sprichwort: „Ohne Fleiß …“", a: "kein Preis." },
  { q: "Vervollständige folgendes Sprichwort: „Hochmut kommt …“", a: "vor dem Fall." },
  { q: "Vervollständige folgendes Sprichwort: „Schuster, bleib bei deinen ...“", a: "Leisten." },
  // ===== Filmzitate ===== //
{ q: "Das Filmzitat \"Möge die Macht mit dir sein\" stammt aus welchem bekannten Film?", a: "Star Wars" },
{ q: "Das Filmzitat \"I'll be back!\" stammt aus welchem bekannten Film?", a: "Terminator" },
{ q: "Das Filmzitat \"Hasta la vista, Baby\" stammt aus welchem bekannten Film?", a: "Terminator 2" },
{ q: "Das Filmzitat \"Houston, wir haben ein Problem\" stammt aus welchem bekannten Film?", a: "Apollo 13" },
{ q: "Das Filmzitat \"Schau mir in die Augen, Kleines\" stammt aus welchem bekannten Film?", a: "Casablanca" },
{ q: "Das Filmzitat \"Hier ist Johnny!\" stammt aus welchem bekannten Film?", a: "Shining" },
{ q: "Das Filmzitat \"Ich bin der König der Welt!\" stammt aus welchem bekannten Film?", a: "Titanic" },
{ q: "Das Filmzitat \"Sag Hallo zu meinem kleinen Freund!\" stammt aus welchem bekannten Film?", a: "Scarface" },
{ q: "Das Filmzitat \"Das ist Sparta!\" stammt aus welchem bekannten Film?", a: "300" },
{ q: "Das Filmzitat \"Niemand setzt Baby in die Ecke\" stammt aus welchem bekannten Film?", a: "Dirty Dancing" },
{ q: "Das Filmzitat \"Nach Hause telefonieren\" stammt aus welchem bekannten Film?", a: "E.T." },
{ q: "Das Filmzitat \"Mein Schatz\" stammt aus welchem bekannten Film?", a: "Der Herr der Ringe" },
{ q: "Das Filmzitat \"Zeig mir das Geld!\" stammt aus welchem bekannten Film?", a: "Jerry Maguire" },
{ q: "Das Filmzitat \"You can’t handle the truth!\" stammt aus welchem bekannten Film?", a: "Eine Frage der Ehre" },
{ q: "Das Filmzitat \"Ich sehe tote Menschen\" stammt aus welchem bekannten Film?", a: "The Sixth Sense" },
{ q: "Das Filmzitat \"Das Leben ist wie eine Schachtel Pralinen\" stammt aus welchem bekannten Film?", a: "Forrest Gump" },
{ q: "Das Filmzitat \"Ein Ring, sie zu knechten\" stammt aus welchem bekannten Film?", a: "Der Herr der Ringe" },
  // ===== Mathe-Begriffe ===== //
{ q: "Wie nennt man in der Mathematik die Zahl, die sich unter dem Bruchstrich befindet", a: "Nenner" },
{ q: "Wie nennt man in der Mathematik die Zahl, die sich über dem Bruchstrich befindet", a: "Zähler" },
{ q: "Die mathematische Gleichung a im Quadrat plus b im Quadrat ist gleich C im Quadrat nennt man auch Satz des ...", a: "Pythagoras" },
{ q: "Das Ergebnis einer Addition nennt man ...", a: "Summe" },
{ q: "Das Ergebnis einer Division nennt man ...", a: "Quotient" },
{ q: "Wie nennt man in der Mathematik die Zahl, die sich unter dem Bruchstrich befindet", a: "Nenner" },
  // ===== Kleines 1 x 1 ===== //
{ q: "5 mal 5 ist ...", a: "25" },
{ q: "6 mal 6 ist ...", a: "36" }, 
{ q: "7 mal 7 ist ...", a: "49" },  
{ q: "8 mal 8 ist ...", a: "64" },
{ q: "9 mal 9 ist ...", a: "81" },
{ q: "3 mal 9 ist ...", a: "27" },
{ q: "4 mal 8 ist ...", a: "32" },
{ q: "5 mal 7 ist ...", a: "35" },
{ q: "3 mal 8 ist ...", a: "24" },
{ q: "4 mal 7 ist ...", a: "28" },
  // ===== Bekannte Lieder ===== //
{ q: "Die Lieder \"Bohemian Rhapsody\", \"We Will Rock You\" und \"Don’t Stop Me Now\" stammen von welcher bekannten Band?", a: "Queen" },
{ q: "Die Lieder \"Uptown Funk\", \"24K Magic\" und \"Just The Way You Are\" stammen von welchem bekannten Musiker?", a: "Bruno Mars" },
{ q: "Die Lieder \"Hello\", \"Someone Like You\" und \"Rolling in the Deep\" stammen von welcher bekannten Musikerin?", a: "Adele" },
{ q: "Die Lieder \"Wake Me Up\", \"Levels\" und \"Hey Brother\" stammen von welchem bekannten Musiker?", a: "Avicii" },
{ q: "Die Lieder \"God’s Plan\", \"Hotline Bling\" und \"One Dance\" stammen von welchem bekannten Musiker?", a: "Drake" },
{ q: "Die Lieder \"Stitches\", \"Treat You Better\" und \"Señorita\" stammen von welchem bekannten Musiker?", a: "Shawn Mendes" },
{ q: "Die Lieder \"Havana\", \"Señorita\" und \"Never Be the Same\" stammen von welcher bekannten Musikerin?", a: "Camila Cabello" },
{ q: "Die Lieder \"Can’t Help Falling in Love\", \"Jailhouse Rock\" und \"Suspicious Minds\" stammen von welchem bekannten Musiker?", a: "Elvis Presley" },
{ q: "Die Lieder \"Hey Jude\", \"Let It Be\" und \"Yesterday\" stammen von welcher bekannten Band?", a: "The Beatles" },
{ q: "Die Lieder \"Billie Jean\", \"Thriller\" und \"Beat It\" stammen von welchem bekannten Musiker?", a: "Michael Jackson" },
{ q: "Die Lieder \"With or Without You\", \"One\" und \"Beautiful Day\" stammen von welcher bekannten Band?", a: "U2" },
{ q: "Die Lieder \"With a Little Help from My Friends\", \"You Are So Beautiful\" und \"Unchain My Heart\" stammen von welchem bekannten Musiker?", a: "Joe Cocker" },
{ q: "Die Lieder \"Lose Yourself\", \"Without Me\" und \"Stan\" stammen von welchem bekannten Musiker?", a: "Eminem" },
{ q: "Die Lieder \"Love Story\", \"Shake It Off\" und \"Blank Space\" stammen von welchem bekannten Musikerin?", a: "Taylor Swift" },
{ q: "Die Lieder \"Roar\", \"Firework\" und \"Teenage Dream\" stammen von welchem bekannten Musikerin?", a: "Katy Perry" },
{ q: "Die Lieder \"Watermelon Sugar\", \"Sign of the Times\" und \"As It Was\" stammen von welchem bekannten Musiker?", a: "Harry Styles" },
{ q: "Die Lieder \"Chandelier\", \"Cheap Thrills\" und \"Elastic Heart\" stammen von welcher bekannten Musikerin?", a: "Sia" },
{ q: "Die Lieder \"Born in the U.S.A.\", \"Dancing in the Dark\" und \"Streets of Philadelphia\" stammen von welchem bekannten Musiker?", a: "Bruce Springsteen" },
{ q: "Die Lieder \"Livin’ on a Prayer\", \"You Give Love a Bad Name\" und \"It’s My Life\" stammen von welchem bekannten Musiker?", a: "Jon Bon Jovi" },
{ q: "Die Lieder \"Sonderzug nach Pankow\", \"Cello\" und \"Horizont\" stammen von welchem bekannten Musiker?", a: "Udo Lindenberg" },
{ q: "Die Lieder \"Dieser Weg\", \"Wo willst du hin?\" und \"Sie sieht mich nicht\" stammen von welchem bekannten Musiker?", a: "Xavier Naidoo" },
{ q: "Die Lieder \"Griechischer Wein\", \"Aber bitte mit Sahne\" und \"Mit 66 Jahren\" stammen von welchem bekannten Musiker?", a: "Udo Jürgens" },
{ q: "Die Lieder \"Chöre\", \"Au revoir\" und \"Übermorgen\" stammen von welchem bekannten Musiker?", a: "Mark Forster" },
  // ===== Universum ===== //
  { q: "Welcher Planet wird als der rote Planet bezeichnet?", a: "Mars" },
  { q: "Welcher Planet ist in unserem Sonnensystem von der Erde am weitesten entfernt?", a: "Neptun" },
  { q: "Welcher Planet ist in unserem Sonnensystem der größte?", a: "Jupiter" },
  { q: "Welcher Planet in unserem Sonnensystem gilt als der größte Gasplanet im Sonnensystem?", a: "Jupiter" },
  { q: "Welcher Planet ist in unserem Sonnensystem der Sonne am nächsten?", a: "Merkur" },
  { q: "Welcher Planet wird auch der rote Planet genannt?", a: "Mars" },
  { q: "Welcher Planet ist in unserem Sonnensystem bekannt für seine auffälligen Ringe?", a: "Saturn" },
  { q: "Wie heißt unsere Galaxie, in der sich auch die Erde befindet?", a: "Milchstraße" },
  { q: "Welcher Stern steht im Zentrum unseres Sonnensystems?", a: "Sonne" },
  { q: "Welcher Planet dreht sich am schnellsten um seine eigene Achse?", a: "Jupiter" },
  { q: "Welcher Planet hat die längste Umlaufzeit um die Sonne?", a: "Neptun" },
  { q: "Welcher Planet ist nach dem römischen Gott des Meeres benannt?", a: "Neptun" },
  { q: "Welcher Planet hat die längste Tagesdauer im Sonnensystem?", a: "Venus" },
  { q: "Wie heißt der Zwergplanet, der früher als neunter Planet galt?", a: "Pluto" },
  { q: "Welcher Planet hat die meisten bekannten Monde?", a: "Jupiter" },
  { q: "Welcher Planet ist der kleinste im Sonnensystem?", a: "Merkur" },
 // ===== Werbeslogans ===== //
  { q: "Der Werbeslogan \"Vorsprung durch Technik\" gehört zu welcher bekannten Marke?", a: "Audi" },
  { q: "Der Werbeslogan \"Nonstop you\" gehört zu welcher Fluggesellschaft?", a: "Lufthansa" },
  { q: "Der Werbeslogan \"Geiz ist geil\" gehört zu welcher deutschen Elektronikkette?", a: "Saturn" },
  { q: "Der Werbeslogan \"Leistung aus Leidenschaft\" gehört zu welcher Bank?", a: "Deutsche Bank" },
  { q: "Der Werbeslogan \"Quadratisch. Praktisch. Gut.\" gehört zu welcher bekannten Schokoladenmarke?", a: "Ritter Sport" },
  { q: "Der Werbeslogan \"Draußen zu Hause\" gehört zu welcher Outdoor-Marke?", a: "Jack Wolfskin" },
  { q: "Der Werbeslogan \"Respekt, wer’s selber macht\" gehört zu welcher deutschen Baumarktkette?", a: "Toom" },
  { q: "Der Werbeslogan \"Just do it.\" gehört zu welcher bekannten Sportmarke?", a: "Nike" },
  { q: "Der Werbeslogan \"Think different.\" gehört zu welcher weltbekannten Technologiefirma?", a: "Apple" },
  { q: "Der Werbeslogan \"Freude am Fahren\" gehört zu welchem deutschen Autohersteller?", a: "BMW" },
  { q: "Der Werbeslogan \"I’m lovin’ it\" gehört zu welcher weltbekannten Fast-Food-Kette?", a: "McDonald’s" },
  { q: "Der Werbeslogan \"Nichts ist unmöglich\" gehört zu welcher bekannten Marke?", a: "Toyota" },
  { q: "Der Werbeslogan \"Wir lieben Lebensmittel\" gehört zu welcher bekannten Unternehmenskette?", a: "Edeka" },
  { q: "Der Werbeslogan \"Taste the rainbow\" gehört zu welcher bekannten Marke?", a: "Skittles" },
  { q: "Der Werbeslogan \"Bier, das uns zu Freunden macht\" gehört zu welcher Marke?", a: "König Pilsener" },
  { q: "Der Werbeslogan \"Finger lickin’ good\" gehört zu welcher Fast-Food-Kette?", a: "KFC" },
 // ===== Spitznamen Fußballvereine ===== //
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Roten Teufel\"?", a: "1. FC Kaiserslautern" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Fohlen\"?", a: "Borussia Mönchengladbach" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Knappen\"?", a: "FC Schalke 04" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Eisernen\"?", a: "1. FC Union Berlin" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Werkself\"?", a: "Bayer 04 Leverkusen" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Rothosen\"?", a: "Hamburger SV" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Breisgauer\"?", a: "SC Freiburg" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Schwaben\"?", a: "VfB Stuttgart" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Geißböcke\"?", a: "1. FC Köln" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Lilien\"?", a: "SV Darmstadt 98" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Fuggerstädter\"?", a: "FC Augsburg" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Alte Dame\"?", a: "Hertha BSC" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Wölfe\"?", a: "VfL Wolfsburg" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die 96er\"?", a: "Hannover 96" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Löwen\"?", a: "TSV 1860 München" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Schanzer\"?", a: "FC Ingolstadt 04" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Zebras\"?", a: "MSV Duisburg" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Kleeblätter\"?", a: "SpVgg Greuther Fürth" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Eisernen Adler\"?", a: "Eintracht Frankfurt" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Störche\"?", a: "Holstein Kiel" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Kiezkicker\"?", a: "FC St. Pauli" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Sachsen\"?", a: "RB Leipzig" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Die Fortuna\"?", a: "Fortuna Düsseldorf" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Red Devils\"?", a: "Manchester United" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Gunners\"?", a: "Arsenal FC" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Citizens\"?", a: "Manchester City" },
  { q: "Welcher Fußballverein trägt den Spitznamen \"Blaugrana\"?", a: "FC Barcelona" },
  // ===== Sprachen ===== //
  { q: "Wenn man mit dem Wort \"Merhaba\" begrüßt wird, ist man in welchem Land?", a: "Türkei" },
  { q: "Wenn man mit dem Wort \"Kon'nichiwa\" begrüßt wird, ist man in welchem Land?", a: "Japan" },
  { q: "Wenn man mit dem Wort \"Ni hao\" begrüßt wird, ist man in welchem Land?", a: "China" }, 
  { q: "Wenn man mit dem Wort \"Namaste\" begrüßt wird, ist man in welchem Land?", a: "Indien" },   
   // ===== Sonstiges ===== //
  { q: "Das Oktoberfest in München beginnt in welchem Monat?", a: "September" },  
  { q: "Welches berühmte Wirtschaftsmagazin listet jedes Jahr die reichsten Menschen der Welt auf?", a: "Forbes" },
  { q: "Welche Farbe hat das N im Netflix-Logo?", a: "Rot" },
  { q: "Welche Farbe hat das L im Google-Logo?", a: "Grün" },
  { q: "Wie nennt man den Prozess, bei dem Lichtenergie genutzt wird, um aus Wasser und Kohlendioxid Sauerstoff zu erzeugen?", a: "Photosynthese" },
   // ===== Rechtschreibung ===== //
  { q: "Schreibt man das Wort \"Joghurt\" mit oder ohne H?", a: "Mit" },
  // ===== Aus wie vielen Buchstaben ===== //
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Banane\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Tasche\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Blumen\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Karten\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Bruder\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Kuchen\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Kerzen\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Fische\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Tanzen\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Lachen\"?", a: "6" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Fenster\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Kirsche\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Zeitung\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Samstag\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Zeichen\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Familie\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Kapitel\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Wandern\"?", a: "7" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Freiheit\"", a: "8" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Männlein\"", a: "8" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Tonfigur\"", a: "8" },
{ q: "Aus wie vielen Buchstaben besteht das Wort \"Jubiläum\"", a: "8" },
  // ===== Sport ===== //
{ q: "In welcher Sportart bricht der Schwede Armand Duplantis regelmäßig seine eigenen Weltrekorde?", a: "Stabhochsprung" },
{ q: "Der aktuelle Weltrekord im 100-Meter-Sprint wurde von dem Jamaikaner Usain Bolt im Jahr 2009 aufgestellt. Liegt die benötigte Zeit über oder unter 10,00 Sekunden?", a: "Unter" },
{ q: "In welcher Sportart teilten sich der Katarer Mutaz Essa Barshim und Italiener Gianmarco Tamberi bei den olympischen Spielen 2020 eine Goldmedaille?", a: "Hochsprung" }
];
// ---------------------------------------------
