// questions.js
// ---------------------------------------------
window.QUESTION_POOL = [
  // ===== Hauptstädte ===== //
  { q: "Die Hauptstadt von Frankreich ist …", a: "Paris" },
  { q: "Die Hauptstadt von Italien ist …", a: "Rom" },
  { q: "Die Hauptstadt von Schweiz ist …", a: "Bern" },
  { q: "Die Hauptstadt von Spanien ist …", a: "Madrid" },
  { q: "Die Hauptstadt von Portugal ist …", a: "Lissabon" },
  { q: "Die Hauptstadt von Norwegen ist …", a: "Oslo" },
  { q: "Die Hauptstadt von Schweden ist …", a: "Stockholm" },
  { q: "Die Hauptstadt von Finnland ist …", a: "Helsinki" },
  { q: "Die Hauptstadt von Polen ist …", a: "Warschau" },
  { q: "Die Hauptstadt von Tschechien ist …", a: "Prag" },
  { q: "Die Hauptstadt von Malta ist …", a: "Valletta" },
  { q: "Die Hauptstadt von Türkei ist …", a: "Ankara" },
  { q: "Die Hauptstadt von Zypern ist …", a: "Nikosia" },
  { q: "Die Hauptstadt von Griechenland ist …", a: "Athen" },
  { q: "Die Hauptstadt von Bulgarien ist …", a: "Sofia" },
  { q: "Die Hauptstadt von Ukraine ist …", a: "Kiew" },
  { q: "Die Hauptstadt von Rumänien ist …", a: "Bukarest" },
  { q: "Die Hauptstadt von China ist …", a: "Peking (Beijing)" },
  { q: "Die Hauptstadt von Indien ist …", a: "Neu-Delhi" },
  { q: "Die Hauptstadt von Pakistan ist …", a: "Islamabad" },
  { q: "Die Hauptstadt von Philippinen ist …", a: "Manila" },
  { q: "Die Hauptstadt von Australien ist …", a: "Canberra" },
  { q: "Die Hauptstadt von Neuseeland ist …", a: "Wellington" },
  { q: "Die Hauptstadt von Brasilien ist …", a: "Brasília" },
  { q: "Die Hauptstadt von Argentinien ist …", a: "Buenos Aires" },
  { q: "Die Hauptstadt von Kolumbien ist …", a: "Bogotá" },
  { q: "Die Hauptstadt von Kanada ist …", a: "Ottawa" },
  { q: "Die Hauptstadt von Mexiko ist …", a: "Mexiko-Stadt" },
  { q: "Die Hauptstadt von Vereinigte Staaten ist …", a: "Washington, D.C." },
  { q: "Die Hauptstadt von Tunesien ist …", a: "Tunis" },
  { q: "Die Hauptstadt von Südafrika ist …", a: "Pretoria" },
  { q: "Die Hauptstadt von Ägypten ist …", a: "Kairo" },
  { q: "Die Hauptstadt von Algerien ist …", a: "Algier" },
  { q: "Die Hauptstadt von Marokko ist …", a: "Rabat" },
  { q: "Die Hauptstadt von Japan ist …", a: "Tokio" },
  { q: "Die Hauptstadt von Südkorea ist …", a: "Seoul" },
  { q: "Die Hauptstadt von Nordkorea ist …", a: "Pjöngjang" },
  { q: "Die Hauptstadt von Vietnam ist …", a: "Hanoi" },
  // ===== US-Politik ===== //
  { q: "Der wievielte US-Präsident war George Washington?", a: "1" },
  { q: "Der wievielte US-Präsident war Joe Biden?", a: "46" },
  { q: "Joe Biden schlug im US-Präsidentschaftswahlkampf seinen republikanischen Gegenkandidaten Donald ...“, a: "Trump" },
  { q: "Wie viele Sterne sind auf der US-Flagge?", a: "50" },
  { q: "Welches Tier ist das Symbol der Demokratischen Partei?", a: "Esel" },
  { q: "Welches Tier ist das Symbol der Republikanischen Partei?", a: "Elefant" },
  { q: "Wie viele Senatoren gibt es im US-Senat?", a: "100" },
  { q: "Wie oft können US-Präsidenten gewählt werden?", a: "Zweimal" },
  { q: "Wie heißt der Skandal, der 1974 zum Rücktritt von Präsident Richard Nixon führte?", a: "Watergate-Skandal" },
  { q: "Wie nennt man US-Bundesstaaten, in denen keine der beiden großen Parteien eine verlässliche Mehrheit hat und in dem die Mehrheit hin- und herwechseln kann?", a: "Swing States" },
  { q: "Wie nennt man das Gremium, das in den USA den Präsidenten offiziell wählt?", a: "Electoral College" },
  { q: "Was ist ein gängiger Begriff für einen Präsidenten, der zwar noch im Amt ist, aber bereits abgewählt oder amtszeitbeschränkt ist?", a: "Lame Duck" },
  { q: "Wie heißt das Büro des US-Präsidenten im Weißen Haus?", a: "Oval Office" },
  { q: "Die ehemalige Praktikantin, die bekannt dafür wurde eine Affäre mit US-Präsident Bill Clinton zu haben, hieß Monica ...", a: "Lewinsky" },
  // ===== Reime ===== //
  { q: "Welches optische Hilfsmittel reimt sich auf Stille?", a: "Brille" },
  { q: "Welches Alltagswerkzeug reimt sich auf Klammer?", a: "Hammer" },
  // ===== KFZ-Kennzeichen ===== //
  { q: "Das KFZ-Kennzeichen HB steht für welche deutsche Stadt?", a: "Bremen" },
  { q: "Das KFZ-Kennzeichen HH steht für welche deutsche Stadt?", a: "Hamburg" },
  { q: "Das KFZ-Kennzeichen B steht für welche deutsche Stadt?", a: "Berlin" },
  { q: "Das KFZ-Kennzeichen M steht für welche deutsche Stadt?", a: "München" },
  { q: "Das KFZ-Kennzeichen K steht für welche deutsche Stadt?", a: "Köln" },
  { q: "Das KFZ-Kennzeichen DD steht für welche deutsche Stadt?", a: "Dresden" },
  { q: "Das KFZ-Kennzeichen DO steht für welche deutsche Stadt?", a: "Dortmund" },
  { q: "Das KFZ-Kennzeichen DU steht für welche deutsche Stadt?", a: "Duisburg" },
  { q: "Das KFZ-Kennzeichen E steht für welche deutsche Stadt?", a: "Essen" },
  { q: "Das KFZ-Kennzeichen F steht für welche deutsche Stadt?", a: "Frankfurt am Main" },
  { q: "Das KFZ-Kennzeichen S steht für welche deutsche Stadt?", a: "Stuttgart" },
  { q: "Das KFZ-Kennzeichen H steht für welche deutsche Stadt?", a: "Hannover" },
  { q: "Das KFZ-Kennzeichen N steht für welche deutsche Stadt?", a: "Nürnberg" },
  { q: "Das KFZ-Kennzeichen MA steht für welche deutsche Stadt?", a: "Mannheim" },
  { q: "Das KFZ-Kennzeichen WOB steht für welche deutsche Stadt?", a: "Wolfsburg" },
  // ===== vor oder nach Chr. ===== //
  { q: "Der griechische Philosoph Sokrates starb 399 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Platon wurde 427 v. Chr. oder n. Chr. geboren?", a: "v. Chr." },
  { q: "Der Feldherr Alexander der Große starb 323 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der römische Diktator Julius Cäsar starb 44 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der römische Kaiser Augustus starb 14 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Jesus von Nazareth wurde um das Jahr 4 v. Chr. oder n. Chr. geboren?", a: "v. Chr." },
  { q: "Der römische Kaiser Nero starb 68 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der griechische Mathematiker Archimedes starb 212 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Aristoteles starb 322 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Feldherr Hannibal lebte 2. Jahrhundert v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Apostel Paulus starb um 64 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der ägyptische Pharao Tutanchamun starb um 1323 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Die Königin Kleopatra starb 30 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Konfuzius starb 479 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der römische Kaiser Konstantin der Große starb 337 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der jüdische König Herodes der Große starb 4 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Feldherr Spartakus starb 71 v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Philosoph Seneca starb 65 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der Dichter Homer lebte im 8. Jahrhundert v. Chr. oder n. Chr.?", a: "v. Chr." },
  { q: "Der Apostel Paulus starb um 64 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Nero starb 68 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Augustus starb 14 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Tiberius starb 37 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der Apostel Petrus starb um 64 v. Chr. oder n. Chr.?", a: "n. Chr." },
  { q: "Der römische Kaiser Caligula starb 41 v. Chr. oder n. Chr.?", a: "n. Chr." },
  // ===== Primzahl ===== //
  { q: "Welche Primzahl folgt auf 23?", a: "29" },
  { q: "Welche Primzahl folgt auf 29?", a: "31" },
  { q: "Welche Primzahl folgt auf 31?", a: "37" },
  { q: "Welche Primzahl folgt auf 37?", a: "41" },
  { q: "Welche Primzahl folgt auf 41?", a: "43" },
  { q: "Welche Primzahl folgt auf 43?", a: "47" },
  { q: "Welche Primzahl folgt auf 47?", a: "53" },
  { q: "Welche Primzahl folgt auf 53?", a: "59" },
  { q: "Welche Primzahl folgt auf 59?", a: "61" },
  { q: "Welche Primzahl folgt auf 61?", a: "67" },
  // ===== Sprichwörter ===== //
  { q: "Vervollständige folgendes Sprichwort: „Wer anderen eine Grube gräbt, …“", a: "fällt selbst hinein." },
  { q: "Vervollständige folgendes Sprichwort: „Morgenstund hat …“", a: "Gold im Mund." },
  { q: "Vervollständige folgendes Sprichwort: „Alle Wege führen …“", a: "nach Rom." },
  { q: "Vervollständige folgendes Sprichwort: „Ende gut, …“", a: "alles gut." },
  { q: "Vervollständige folgendes Sprichwort: „Stille Wasser sind …“", a: "tief." },
  { q: "Vervollständige folgendes Sprichwort: „Übung macht …“", a: "den Meister." },
  { q: "Vervollständige folgendes Sprichwort: „Eile mit …“", a: "Weile." },
  { q: "Vervollständige folgendes Sprichwort: „Kleider machen …“", a: "Leute." },
  { q: "Vervollständige folgendes Sprichwort: „Wie man in den Wald hineinruft, …“", a: "so schallt es heraus." },
  { q: "Vervollständige folgendes Sprichwort: „Der Apfel fällt nicht …“", a: "weit vom Stamm." },
  { q: "Vervollständige folgendes Sprichwort: „Viele Köche …“", a: "verderben den Brei." },
  { q: "Vervollständige folgendes Sprichwort: „Man soll den Tag nicht …“", a: "vor dem Abend loben." },
  { q: "Vervollständige folgendes Sprichwort: „Eine Hand wäscht …“", a: "die andere." },
  { q: "Vervollständige folgendes Sprichwort: „Der frühe Vogel …“", a: "fängt den Wurm." },
  { q: "Vervollständige folgendes Sprichwort: „In der Not frisst …“", a: "der Teufel Fliegen." },
  { q: "Vervollständige folgendes Sprichwort: „Was du nicht willst, das man dir tu, …“", a: "das füg auch keinem andern zu." },
  { q: "Vervollständige folgendes Sprichwort: „Wer rastet, …“", a: "der rostet." },
  { q: "Vervollständige folgendes Sprichwort: „Ein Unglück kommt …“", a: "selten allein." },
  { q: "Vervollständige folgendes Sprichwort: „Aus den Augen, …“", a: "aus dem Sinn." },
  { q: "Vervollständige folgendes Sprichwort: „Lügen haben …“", a: "kurze Beine." },
  { q: "Vervollständige folgendes Sprichwort: „Was lange währt, …“", a: "wird endlich gut." },
  { q: "Vervollständige folgendes Sprichwort: „Geteiltes Leid ist …“", a: "halbes Leid." },
  { q: "Vervollständige folgendes Sprichwort: „Reden ist Silber, …“", a: "Schweigen ist Gold." },
  { q: "Vervollständige folgendes Sprichwort: „Wer zuletzt lacht, …“", a: "lacht am besten." },
  { q: "Vervollständige folgendes Sprichwort: „Der Fisch stinkt vom …“", a: "Kopf her." },
  { q: "Vervollständige folgendes Sprichwort: „Not macht …“", a: "erfinderisch." },
  { q: "Vervollständige folgendes Sprichwort: „Liebe geht durch …“", a: "den Magen." },
  { q: "Vervollständige folgendes Sprichwort: „Ohne Fleiß …“", a: "kein Preis." },
  { q: "Vervollständige folgendes Sprichwort: „Hochmut kommt …“", a: "vor dem Fall." },
  { q: "Vervollständige folgendes Sprichwort: „Schuster, bleib bei …“", a: "deinen Leisten." }
];
// ---------------------------------------------
