// questions.js
// ---------------------------------------------
window.QUESTION_POOL = [
  // ===== Hauptstädte ===== //
  { q: "Die Hauptstadt von Frankreich ist …", a: "Paris" },
  { q: "Die Hauptstadt von Italien ist …", a: "Rom" },
  { q: "Die Hauptstadt von Schweiz ist …", a: "Bern" },
  { q: "Die Hauptstadt von Spanien ist …", a: "Madrid" },
  { q: "Die Hauptstadt von Portugal ist …", a: "Lissabon" },
  { q: "Die Hauptstadt von Norwegen ist …", a: "Oslo" },
  { q: "Die Hauptstadt von Schweden ist …", a: "Stockholm" },
  { q: "Die Hauptstadt von Finnland ist …", a: "Helsinki" },
  { q: "Die Hauptstadt von Polen ist …", a: "Warschau" },
  { q: "Die Hauptstadt von Tschechien ist …", a: "Prag" },
  { q: "Die Hauptstadt von Malta ist …", a: "Valletta" },
  { q: "Die Hauptstadt von Türkei ist …", a: "Ankara" },
  { q: "Die Hauptstadt von Zypern ist …", a: "Nikosia" },
  { q: "Die Hauptstadt von Griechenland ist …", a: "Athen" },
  { q: "Die Hauptstadt von Bulgarien ist …", a: "Sofia" },
  { q: "Die Hauptstadt von Ukraine ist …", a: "Kiew" },
  { q: "Die Hauptstadt von Rumänien ist …", a: "Bukarest" },
  { q: "Die Hauptstadt von China ist …", a: "Peking (Beijing)" },
  { q: "Die Hauptstadt von Indien ist …", a: "Neu-Delhi" },
  { q: "Die Hauptstadt von Pakistan ist …", a: "Islamabad" },
  { q: "Die Hauptstadt von Philippinen ist …", a: "Manila" },
  { q: "Die Hauptstadt von Australien ist …", a: "Canberra" },
  { q: "Die Hauptstadt von Neuseeland ist …", a: "Wellington" },
  { q: "Die Hauptstadt von Brasilien ist …", a: "Brasília" },
  { q: "Die Hauptstadt von Argentinien ist …", a: "Buenos Aires" },
  { q: "Die Hauptstadt von Kolumbien ist …", a: "Bogotá" },
  { q: "Die Hauptstadt von Kanada ist …", a: "Ottawa" },
  { q: "Die Hauptstadt von Mexiko ist …", a: "Mexiko-Stadt" },
  { q: "Die Hauptstadt von Vereinigte Staaten ist …", a: "Washington, D.C." },
  { q: "Die Hauptstadt von Tunesien ist …", a: "Tunis" },
  { q: "Die Hauptstadt von Südafrika ist …", a: "Pretoria" },
  { q: "Die Hauptstadt von Ägypten ist …", a: "Kairo" },
  { q: "Die Hauptstadt von Algerien ist …", a: "Algier" },
  { q: "Die Hauptstadt von Marokko ist …", a: "Rabat" },
  { q: "Die Hauptstadt von Japan ist …", a: "Tokio" },
  { q: "Die Hauptstadt von Südkorea ist …", a: "Seoul" },
  { q: "Die Hauptstadt von Nordkorea ist …", a: "Pjöngjang" },
  { q: "Die Hauptstadt von Vietnam ist …", a: "Hanoi" },
  // ===== US-Politik ===== //
  { q: "Der wievielte US-Präsident war George Washington?", a: "1" },
  { q: "Der wievielte US-Präsident war Joe Biden?", a: "46" },
  { q: "Joe Biden schlug im US-Präsidentschaftswahlkampf seinen republikanischen Gegenkandidaten Donald ...“, a: "Trump" },
  { q: "Wie viele Sterne sind auf der US-Flagge?", a: "50" },
  { q: "Welches Tier ist das Symbol der Demokratischen Partei?", a: "Esel" },
  { q: "Welches Tier ist das Symbol der Republikanischen Partei?", a: "Elefant" },
  { q: "Wie viele Senatoren gibt es im US-Senat?", a: "100" },
  { q: "Wie oft können US-Präsidenten gewählt werden?", a: "Zweimal" },
  { q: "Wie heißt der Skandal, der 1974 zum Rücktritt von Präsident Richard Nixon führte?", a: "Watergate-Skandal" },
  { q: "Wie nennt man US-Bundesstaaten, in denen keine der beiden großen Parteien eine verlässliche Mehrheit hat und in dem die Mehrheit hin- und herwechseln kann?", a: "Swing States" },
  { q: "Wie nennt man das Gremium, das in den USA den Präsidenten offiziell wählt?", a: "Electoral College" },
  { q: "Was ist ein gängiger Begriff für einen Präsidenten, der zwar noch im Amt ist, aber bereits abgewählt oder amtszeitbeschränkt ist?", a: "Lame Duck" },
  { q: "Wie heißt das Büro des US-Präsidenten im Weißen Haus?", a: "Oval Office" },
  { q: "Die ehemalige Praktikantin, die bekannt dafür wurde eine Affäre mit US-Präsident Bill Clinton zu haben, hieß Monica ...", a: "Lewinsky" },
  // ===== Reime ===== //

];
// ---------------------------------------------
